openai:
  model: gpt-4
  api_key_env: OPENAI_API_KEY
  endpoint: https://api.openai.com/v1/chat/completions

claude:
  model: claude-3-opus-20240229
  api_key_env: CLAUDE_API_KEY
  endpoint: https://api.anthropic.com/v1/messages
  headers:
    anthropic-version: "2023-06-01"
    content-type: application/json

gemini:
  model: gemini-2.0-flash
  api_key_env: GEMINI_API_KEY
  endpoint: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$API_KEY